version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_DB: teamsparta_vector
      POSTGRES_USER: rtan
      POSTGRES_PASSWORD: sparta
      # 추가 설정
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - ${DB_HOME}/data/postgres:/var/lib/postgresql/data # Persist data outside the container
      - ${PROJECT_ROOT}/week-03-project/src/main/resources/static/init-db:/docker-entrypoint-initdb.d
      # - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=vector